
rocketmq:
  name-server: localhost:29876 # rocketmq.name-server
  producer:
    group: my-group
    send-message-timeout: 30000
    compress-message-body-threshold: 4096
    max-message-size: 4194304
    retry-times-when-send-async-failed: 0
    retry-next-server: true
    retry-times-when-send-failed: 2
    # 消息轨迹
    enable-msg-trace: true
    customized-trace-topic: my-trace-topic
  demo:
    ext-name-server: 127.0.0.1:29876
    topic: string-topic
    order-topic: order-paid-topic
    msg-ext-topic: message-ext-topic
    trans-topic: spring-transaction-topic
