logging:
  file: D:/mylog/log.log
  level:
    org:
      springframework:
        web: DEBUG

spring:
  datasource:
    url: jdbc:mysql://172.17.101.62:3306/user?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true #\u5F00\u542F\u9A7C\u5CF0\u6620\u5C04

