server:
  port: 8080
  servlet:
    context-path: /api

logging:
  file: ./logs/log.txt
  level:
    org:
      springframework:
        web: debug

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sample?useSSL=false
    username: root
    password: rainbow123
    driver-class-name: com.mysql.jdbc.Driver
#    schema-username:
#    schema-password:
#    data-username:
#    data-password:
    platform: mysql
    schema: classpath:sql/schema.sql
    data: classpath:sql/data.sql
    continue-on-error: true
    initialization-mode: always

article:
  name: spring inaction
  author: Craig Walls
