
auth-server: http://localhost:8085/sso

server:
  port: 8086


spring:
  main:
    allow-bean-definition-overriding: true

security:
  oauth2:
    client:
      client-id: client1
      client-secret: 123456
      user-authorization-uri: ${auth-server}/oauth/authorize
      access-token-uri: ${auth-server}/oauth/token
    resource:
      jwt:
        key-uri: ${auth-server}/oauth/token_key